services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
            target: development
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        ports:
            - "3000:3000"
        command: npm run start:dev
